language: php

sudo: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - 'nightly'

matrix:
  allow_failures:
    - php: 'nightly'
  fast_finish: true

before_install:
  - travis_retry composer self-update
  - travis_retry composer global require --dev phpunit/phpunit ^5.7

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer phpunit
